In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector =np.array([1,2,3])
matriz =np.array([[1,2],[3,4]])
tensor=np.array([[
    [1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
 ])

In [3]:
escalar_t=escalar.t

AttributeError: 'float' object has no attribute 't'

In [4]:
vector_t=vector.T
print(vector_t)

[1 2 3]


In [5]:
matriz_t=matriz.T
print(matriz_t)

[[1 3]
 [2 4]]


In [6]:
print(matriz.shape)

(2, 2)


In [7]:
print(matriz_t.shape)

(2, 2)


In [8]:
tensor_t=tensor.T
print(tensor_t)

[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


In [11]:
A=matriz
B=matriz_t
C=A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[2 5]
 [5 8]]


In [12]:
D=matriz+escalar
print(D)

[[6.679 7.679]
 [8.679 9.679]]


In [24]:
nuevamatriz=np.array([[1,2,3,4,5],
    [10,9,8,7,6],
    [11,12,13,14,15],
    [20,19,18,17,16],
    [21,22,23,24,25]])
print(nuevamatriz)

[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [11 12 13 14 15]
 [20 19 18 17 16]
 [21 22 23 24 25]]


In [25]:
nuevamatriz_t=nuevamatriz.T
a=nuevamatriz
b=nuevamatriz_t
c=a+b
print(c)

[[ 2 12 14 24 26]
 [12 18 20 26 28]
 [14 20 26 32 38]
 [24 26 32 34 40]
 [26 28 38 40 50]]
