In [2]:
import numpy as np

In [3]:
escalar =5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [4]:
A=vector +matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [6]:
A = matriz.T + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [7]:
C = matriz +42
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [9]:
D = matriz + np.array([[42],[42],[42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


In [10]:
nuevovector = np.array([1,2,3,4,5])
nuevamatriz = np.array([[1,2,3,4,5],
    [10,9,8,7,6],
    [11,12,13,14,15],
    [20,19,18,17,16],
    [21,22,23,24,25]])
print(nuevovector+nuevamatriz)

[[ 2  4  6  8 10]
 [11 11 11 11 11]
 [12 14 16 18 20]
 [21 21 21 21 21]
 [22 24 26 28 30]]
