In [1]:
import numpy as np

In [20]:
escalar = 5.679
vector = np.array([2,3,4])
matriz = np.array([[1,2,9],[3,4,7],[5,6,8]])

In [21]:
A = matriz * vector

In [22]:
B = matriz.dot(vector)

In [23]:
print(A)


[[ 2  6 36]
 [ 6 12 28]
 [10 18 32]]


In [24]:
print(B)

[44 46 60]


In [25]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[44 46 60]
[44 46 60]


In [26]:
D = vector.dot(matriz)
print(D)

[31 40 71]
